packages:
  - packages/**
  - config/eslint-config
  - config/stylelint-config
  - config/webpack-config

onlyBuiltDependencies:
  - esbuild

overrides:
  typescript: 5.9.3

peerDependencyRules:
  allowedVersions:
    typescript: 5.9.3
