const baseCommonRules = {
  "@stylistic/array-element-newline": ["error", "consistent"],
  "@stylistic/array-bracket-spacing": ["error", "never"],
  "@stylistic/arrow-parens": ["error", "always"],
  "@stylistic/arrow-spacing": "error",
  "@stylistic/brace-style": ["error", "1tbs"],
  "@stylistic/comma-dangle": ["error", "always-multiline"],
  "@stylistic/comma-spacing": ["error", { before: false, after: true }],
  "@stylistic/eol-last": ["error", "always"],
  "@stylistic/function-call-spacing": "error",
  "@stylistic/function-call-argument-newline": ["error", "consistent"],
  "@stylistic/indent": ["error", 2, { SwitchCase: 1 }],
  "@stylistic/key-spacing": ["error", { mode: "strict" }],
  "@stylistic/max-len": [
    "error",
    140,
    2,
    {
      ignoreUrls: true,
      ignoreComments: true,
      ignoreTrailingComments: true,
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
      ignorePattern: "^import [^,]+ from |^export | implements | `.{30,}`",
    },
  ],
  "@stylistic/multiline-ternary": ["error", "always-multiline"],
  "@stylistic/newline-per-chained-call": ["error", { ignoreChainWithDepth: 3 }],
  "@stylistic/no-mixed-operators": "error",
  "@stylistic/no-multiple-empty-lines": ["error", { max: 1 }],
  "@stylistic/no-trailing-spaces": "error",
  "@stylistic/object-curly-spacing": ["error", "always"],
  "@stylistic/object-curly-newline": ["error", { consistent: true }],
  "@stylistic/operator-linebreak": "error",
  "@stylistic/padded-blocks": [
    "error",
    {
      blocks: "never",
      classes: "never",
      switches: "never",
    },
  ],
  "@stylistic/quotes": ["error", "double"],
  "@stylistic/semi": ["error", "always"],
  "@stylistic/space-before-function-paren": [
    "error",
    {
      anonymous: "always",
      named: "never",
      asyncArrow: "always",
    },
  ],

  "rulesdir/sort-imports": "error",
  "rulesdir/no-empty-lines-between-imports": "error",
  "rulesdir/specified-exports": "error",
  "rulesdir/exports-location": "error",
  "rulesdir/no-multiline-object-key": "error",
  "rulesdir/object-prop-newline": "error",
  "rulesdir/mono-imports": "error",
  "rulesdir/arguments-align": "error",
  "rulesdir/no-js-extension-in-import": "error",
  "rulesdir/require-ts-extension-in-import": "off",

  "no-prototype-builtins": "off",
  "no-unused-vars": "off",
  "no-duplicate-imports": "off",
  "no-constant-condition": "warn",
  "no-console": "warn",
  "no-debugger": "warn",
  "prefer-const": "error",
  "no-param-reassign": ["warn", { props: false }],
  "arrow-body-style": ["error", "as-needed"],
  "curly": "error",
  "no-nested-ternary": "error",
  "no-unneeded-ternary": ["error", { defaultAssignment: false }],
  "no-empty": ["error", { allowEmptyCatch: true }],
  "no-empty-function": [
    "error",
    {
      allow: ["methods", "generatorMethods", "getters", "setters", "constructors", "asyncMethods"],
    },
  ],
} as const;

export { baseCommonRules };

